loader:
  extensions: [".pdf", ".docx", ".xlsx", ".pptx", ".txt", ".md"]

splitter:
  chunk_size: 1000
  chunk_overlap: 200
  strategy: "markdown"

embeddings:
  provider: "ollama"
  model: "nomic-embed-text:latest"  #installed on my pc
  base_url: "http://localhost:11434"

llm:
  provider: "ollama"
  model: "tinyllama:latest"
  num_ctx: 2048

metadata:
  config_file: "./v1metadata.yaml"  #TODO

vectorstore:
  url: "http://localhost:6333"  #porta x qdrant installato sul mio pc
  collection_name: "productionAdvancedRAG-collection"
  use_sparse: true
  force_recreate: false

retriever:
  search_type: "hybrid"
  retrieval_strategy: "mmr"
  top_k: 3
  auto_filter: false

logging: 
  level: "INFO"
  console_output: true
  colored: true

#reranker:
#  enabled: true
#  model: "BAAI/bge-reranker-base"
#  top_k: 5
#  initial_k: 20
